# Generated by Django 4.2.6 on 2024-05-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='nivel_educacional',
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='apellidos',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='email',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='nombre',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
