# Generated by Django 4.2.6 on 2024-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodetalles',
            name='pregunta',
            field=models.CharField(choices=[('1', '¿Nombre de tu primera mascota?'), ('2', '¿Juego favorito?'), ('3', '¿Nombre de tu abuel@?'), ('4', '¿lugar nacimiento?')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='respuesta',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
