# Generated by Django 4.2.6 on 2024-05-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuariodetalles_nivel_educacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='nombre',
        ),
    ]
