# Generated by Django 5.0.6 on 2024-06-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_respuesta_alter_mensaje_destinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
