# Generated by Django 5.0.6 on 2024-07-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_titulo_curso_nombre_remove_curso_fecha_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos_inscritos',
            field=models.ManyToManyField(blank=True, to='core.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
