# Generated by Django 4.2.6 on 2024-05-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuariodetalles_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='rut',
        ),
    ]
