# Generated by Django 5.0.6 on 2024-07-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_curso_estudiantes_estudiante_cursos_inscritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
