# Generated by Django 4.2.6 on 2024-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuariodetalles_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodetalles',
            name='rut',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
