# Generated by Django 5.0.6 on 2024-07-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
